### ISSUE TITLE
interactive config creation - checkmarks

### ISSUE THREAD

**Issue by MarkSackerberg** [metaplex-foundation/sugar#119]
using WSL Ubuntu the checkmarks are not turning green when pressing the space bar

![grafik](https://user-images.githubusercontent.com/93528482/164756927-61a21360-0965-477c-bd19-5f3ba3c785ea.png)

**Comment by samuelvanderwaal** [comment]
I think it's probably not going to be possible to fully support every terminal so will close this unless you have any specific suggestions @MarkSackerberg. We can always re-open later.

**Comment by MarkSackerberg** [comment]
We can close that if you want. Surprinsingly I see changing symbols + colors for choosing the upload method though:
![grafik](https://user-images.githubusercontent.com/93528482/167575308-f5542b6d-9e95-48ce-9d01-a398650e66d2.png)
