### ISSUE TITLE
[Bug]: test_item file generated

### ISSUE THREAD

**Issue by samuelvanderwaal** [metaplex-foundation/sugar#176]
### Issue description

Run a `sugar` command that creates a cache file and it will generate a `test_item` file. This is caused by an upstream dependency and has already been fixed upstream but not published. When the upstream package is published we'll bump the version in sugar and this issue will go away.

### Priority this issue should have

Low (slightly annoying)

**Comment by stegaBOB** [comment]
Is this still an issue? I don't entirely understand
