### ISSUE TITLE
[Bug]: error: linker `cc` not found   |   = note: No such file or directory (os error 2)

### ISSUE THREAD

**Issue by ChippuArt** [metaplex-foundation/sugar#215]
### Issue description

![Erroro](https://user-images.githubusercontent.com/103897523/168479175-d2b3e76d-93be-4f46-8a7b-4c151f4ae402.jpg)

### Priority this issue should have

Low (slightly annoying)

**Comment by samuelvanderwaal** [comment]
If this is on Linux or Windows Subsystem Linux (WSL) try installing the `build-essential` dependency. 

```
sudo apt install build-essential
```

**Comment by samuelvanderwaal** [comment]
@ChippuArt did my suggestion resolve this issue for you?

**Comment by ChippuArt** [comment]
Yes it worked well. Just doint it right now. Thank you for your help ✌️
