### ISSUE TITLE
On Ubuntu 20.04 after installing libssl-dev libudev-dev pkg-config - error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by jlankfo** [metaplex-foundation/sugar#218]
![image](https://user-images.githubusercontent.com/81655370/168967652-eb546096-47f7-4a50-bdc5-faeda110ad5e.png)

`ubuntu@ip-172-31-58-144:~/bin$ strings /etc/ld.so.cache | grep libssl
/lib/x86_64-linux-gnu/libssl.so
/lib/x86_64-linux-gnu/libssl3.so
/lib/x86_64-linux-gnu/libssl.so.3
`

libssl is version 3 in Ubuntu 20.04 and I would imagine most other distros. Not sure why it is looking for 1.1

**Comment by hugotkk** [comment]
I have the same issue as well. How can you fix this?

**Comment by hugotkk** [comment]
just realise that `cargo install sugar-cli` works
but got the libssl error with `bash <(curl -sSf https://sugar.metaplex.com/install.sh)`
