### ISSUE TITLE
[Bug]: "No Such File Or Directory" errors should include what file or directory is missing

### ISSUE THREAD

**Issue by samuelvanderwaal** [metaplex-foundation/sugar#221]
### Issue description

Users who get errors like this should be able to know what is the missing or problem file or directory:
![folder](https://user-images.githubusercontent.com/1684605/170329134-c7e65f23-438d-450b-bc89-992f134aee89.jpg)

### Priority this issue should have

Medium (should be fixed soon)

**Comment by ChippuArt** [comment]
I checked the files for the order and found one number missing at arount 889, both the PNG and the JSON. Still I was suprised hashlips is creating such a empty spot. Whatever now I am running sugar launch and I am in the uploading momentum of the tool ✌️❤️😎😎😎

**Comment by febo** [comment]
I am working on a refactoring of the upload so I will address this in it.

**Comment by febo** [comment]
Fixed by #238
