### ISSUE TITLE
[Bug]: AccountNotFound pubkey=<Address>

### ISSUE THREAD

**Issue by milorue** [metaplex-foundation/sugar#240]
### Issue description

- Create candy machine
- run sugar mint
- get error (Mint Failed) AccountNotFound: pubkey=DXckyWoTB7eXcuTDQzVobZjjkwjqyGFDvBfm5TkUxQVr

### Relevant log output

```shell
Candy machine ID: 38Myfv31dK2Vca6Nd8EKcBuZNuRYWuED59SCz7JGbheA
[00:00:00] Mint failed ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 0/5

🛑 Error running command (re-run needed): AccountNotFound: pubkey=DXckyWoTB7eXcuTDQzVobZjjkwjqyGFDvBfm5TkUxQVr
```

### Priority this issue should have

Medium (should be fixed soon)

**Comment by febo** [comment]
Which RPC server are you using? Try switching to `https://ssc-dao.genesysgo.net/` if this is not the one you are using.

**Comment by samuelvanderwaal** [comment]
@milorue were you able to resolve this by switching RPCs?

**Comment by samuelvanderwaal** [comment]
Closed for inactivity.
