### ISSUE TITLE
[Feature]: abilitly to define more than one treasury account

### ISSUE THREAD

**Issue by dohomi** [metaplex-foundation/sugar#282]
### Feature

Currently with the configuration settings it is possible to set `solTreasuryAccount` to a single address. It would be ideal to define multiple addresses to share the profit on the first mint phase.

### Ideal solution or implementation

Accept an array of addresses with shares similar to `creators` setup.

### Alternative solutions or implementations

Is there any other workaround possible? Maybe if the `solTreasuryAccount` would be set to `null` the creators field would be used and the shares defined there would be applied to the mint sale.

**Comment by Sonicfury** [comment]
If you absolutely need to split revenue, you can still use a multisig like [Meanfi](https://meanfi.com/) in the meantime. Then you can stream income directly to as many wallets as you want. That's what I'll be doing

**Comment by dohomi** [comment]
@Sonicfury thanks for your reply I'll look into it

**Comment by samuelvanderwaal** [comment]
@dohomi check out [Hydra](https://github.com/GlassEaters/hydra), this is the kind of thing it is for.
