### ISSUE TITLE
[Bug]: Page Not Found for docs link about "missing collections files in assets folder"

### ISSUE THREAD

**Issue by the-mercenaries-ltd** [metaplex-foundation/sugar#284]
### Issue description

Steps to reproduce:
1. only include 0.png and 0.json in assets folder
2. complete `sugar validate`
3. wrong link given in log output

Better link would be `https://docs.metaplex.com/tools/sugar/preparing-assets` or `https://docs.metaplex.com/tools/sugar/preparing-assets#-image-collectionpng`

### Relevant log output

```shell
+----------------------------------------------+
| ⚠️  MISSING COLLECTION FILES IN ASSETS FOLDER |
+----------------------------------------------+
Check https://docs.metaplex.com/tools/sugar/asset-preparation-and-deployment#collection-assets for the requirements if you want a collection to be set automatically.
```

### Priority this issue should have

Low (slightly annoying)

**Comment by febo** [comment]
This has been fixed by #286
