### ISSUE TITLE
Creating config

### ISSUE THREAD

**Issue by pogotka** [metaplex-foundation/sugar#290]
What is the NFT Storage authentication token? Where I can find it? I'm uploading collection using Sugar

**Comment by febo** [comment]
Instructions on how to get nft.storage token: https://nft.storage/docs/#get-an-api-token

**Comment by pogotka** [comment]
> Instructions on how to get nft.storage token: https://nft.storage/docs/#get-an-api-token

thank you. api token = authentication token?
