### ISSUE TITLE
Deleting.creating candy machine after testing on devnet

### ISSUE THREAD

**Issue by pogotka** [metaplex-foundation/sugar#293]
Error running command (re-run needed): Candy machine from cache does't exist on chain!

What should I do? I tested my assets on devnet but now I want to upload them on mainnet

**Comment by samuelvanderwaal** [comment]
If you're done with your devnet candy machines you can run `sugar withdraw` which will find all the devnet candy machines and delete them. Once you're ready to upload to mainnet you need to use a mainnet RPC: https://docs.metaplex.com/guides/community#services.
