### ISSUE TITLE
[Bug]: output cache.json gives field errors

### ISSUE THREAD

**Issue by priyansh71** [metaplex-foundation/sugar#295]
### Issue description

1. Navigate to any ```assets``` directory with a ```cache.json``` file.
2. Create any new ```asset``` with relevant metadata and image name in the correct format.
3. Run ```sugar launch  .``` to validate and upload the file for deploying it to the **Candy Machine** on Solana.
4. See the error of the missing ```name``` field in the cache.json file
<img width="1246" alt="Screenshot 2022-07-23 at 17 10 16" src="https://user-images.githubusercontent.com/77532581/180603517-08ac1b71-581c-470c-a6b1-d5cf1332d014.png">

5. After fixing this, it asks for the ```description``` field, and so on,  like similar fields to the ```collection.json``` file.
6. Every time a new upload has to be made, the ```cache.json``` must be edited as the output file of the deployment does not give such fields by default.

### Relevant log output

```shell
🛑 Error running command (re-run needed): Validation error: see 'validate_errors.json' file for details

validate_errors.json


[
  {
    "path": "cache.json",
    "error": "missing field `name` at line 1 column 2064"
  }
]
```

### Priority this issue should have

Low (slightly annoying)

**Comment by samuelvanderwaal** [comment]
@priyansh71 don't put your `cache.json` file in your `assets` directory. Any JSON files Sugar finds there it thinks is an asset. The correct folder structure is like this:

```
my_project/
    cache.json
    config.json
    assets/
        0.json
        0.png
        1.json
        1.png
        ...
```

Run sugar commands in the project directory and it will create the cache and config files in the correct place. 

```
my_project:> sugar launch
```
