### ISSUE TITLE
Get my solana tokens back

### ISSUE THREAD

**Issue by Asocial202** [metaplex-foundation/sugar#296]
Hello guys, 
I was trying to mint an nft collection of 1817 nfts with sugar, amazing tool. Everything went ok until deploy phase. Problem was I was trying to mint from public rpc node, bundlr in config.json. My fault.
So, I paid 3 sol for creating a candy machine that did not work. 
I need to know if there is any way to get that sol tokens back.
I already figured out a paid rpc node and was able to complete the sugar launch whole process but now I need more sol to mint the tokens. 
Thank you very much in advance

**Comment by samuelvanderwaal** [comment]
Use the [withdraw command](https://docs.metaplex.com/tools/sugar/commands#withdraw). Read the docs carefully, because it will delete any candy machine you call it on, but that's how you can get your SOL back. Ask in the #sugar channel in Metaplex Discord if you have any questions about it.
