### ISSUE TITLE
[Bug]: When Specifying SPL Token Mint seems the cast to u64 is not allowing for fractional price. 

### ISSUE THREAD

**Issue by thedonmon** [metaplex-foundation/sugar#297]
### Issue description

1. Create an SPL token with any amount of decimals (this will be the mint currency) 
2. Setup the Sugar config with the SPL Mint option
3. Fillout the details and make a price like 1.5 or 2.25 etc 
4. You will see after running `sugar show` the Price will be the first digit rounded up. 
5. In looking through the code it seems there's an attempt to get the correct config price but in what I've tested, if the f64 is casted as a u64 it then rounds to the number that is before the decimal place. Tried to make a quick gist here:
https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=2e25fc55df94978f7d2af2f666c8d292

The relevant code line is here in the sugar program:

https://github.com/metaplex-foundation/sugar/blob/5bb922f3cc9e843269f330300bd159c63af1fadd/src/candy_machine.rs#L31

<img width="280" alt="image" src="https://user-images.githubusercontent.com/22967202/180889703-08fae065-ceb5-45d5-ad33-288c371516fd.png">
<img width="209" alt="image" src="https://user-images.githubusercontent.com/22967202/180889760-224dc680-8f2b-442c-b34f-3742ef571c20.png">

### Priority this issue should have

Medium (should be fixed soon)

**Comment by thedonmon** [comment]
This is also on the latest release v0.5.4

**Comment by samuelvanderwaal** [comment]
@thedonmon thanks for the clear and detailed bug report. I have a [PR](https://github.com/metaplex-foundation/sugar/pull/313) open to fix this now.
