### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by rumblersull** [metaplex-foundation/sugar#299]
### Issue description

I am trying to upload mp4 nfts using Sugar. My json files are also set to mp4 rather than image. At the time of upload, Sugar throws an error that "image" was not found in 0.json. I guess it looks for a png file field in the json and throws an error. Instead, of image I have "animation_url". How can I make  sugar default to mp4 rather than png?

Error running command (re-run needed): Failed to read metadata file 'assets/0.json' with error: missing field `image` at line 61 column 1

### Relevant log output

```shell
Error running command (re-run needed): Failed to read metadata file 'assets/0.json' with error: missing field `image` at line 61 column 1
```

### Priority this issue should have

High (immediate attention needed)

**Comment by MarkSackerberg** [comment]
Hey,
according to the token metadata stabdard you cannot just have the animation_url. You should always also provide a placeholder image for tools and websites that are unable to render your video file.
Therefore this is not a bug from my point of view.

**Comment by rumblersull** [comment]
Hello, noted thanks. I did generate pngs and uploaded both and it all worked out in the end. One issue which does seem like a bug is that Sugar misreads the number of asset pairs in the assets folders at the beginning of the launch process but then does the upload correctly later. This just needs a slight code tweak on metaplex's part.
