### ISSUE TITLE
[Bug]: sugar upload not appending the ext when using Bundlr

### ISSUE THREAD

**Issue by nypam** [metaplex-foundation/sugar#303]
### Issue description

The command sugar upload doesn't append the proper extension to images/animations.
It is problematic for animations as various wallets won't display the video correctly.

My assets folder looks like this:
<img width="176" alt="Screenshot 2022-08-01 at 21 53 05" src="https://user-images.githubusercontent.com/82271058/182233875-81a6e884-d8bf-4d15-8280-fdc1eeb47ee9.png">

This is the JSON file for one of the NFT with the animation_url.
[Token Metadata Standard](https://docs.metaplex.com/programs/token-metadata/token-standard) is respected.
```json
{
    "name": "DEMO BUG",
    "symbol": "BUG",
    "description": "Some description",
    "image": "0.png",
    "animation_url": "0.mp4",
    "external_url": "",
    "attributes": [
        {
          "trait_type": "Item",
          "value": "xxx"
        }
      ],
    "properties": {
      "category": "video",
      "files": [
        {
          "uri": "0.png",
          "type": "image/png"
        },
        {
          "uri": "0.mp4",
          "type": "video/mp4"
        }
      ]
    }
  }
```

After `sugar upload` check **cache.json** and open **metadata_link** for one of the NFT:

```json
{
  "name": "ULTRA GALACTIC ESTHER",
  "symbol": "",
  "description": "Esther stumbles into a peculiar green hue, falling, and finds herself at the Mortuary doorstep. Upon entering, Esther feast her eyes on the tombs in front of her, struck at the opportunity to plunder, loot and play dress-ups.",
  "image": "https://arweave.net/32M4ARiDKDwjLfukYKC378O6FPeWnXnpHh9G2oSpI20",
  "animation_url": "https://arweave.net/yLCKZAAO4GgHhJ8ShhtCpc0g0cVwrBdA3mz7r5enVC8",
  "external_url": "https://www.esthersescape.xyz/esthers-mortuary-plunder",
  "attributes": [
    {
      "trait_type": "ITEM #1",
      "value": "JETPACK"
    },
    {
      "trait_type": "ITEM #2",
      "value": "GOGGLES"
    },
    {
      "trait_type": "ITEM #3",
      "value": "BLASTER CANNON"
    },
    {
      "trait_type": "EYE COUNT",
      "value": "5"
    },
    {
      "trait_type": "STANCE",
      "value": "ANIMATED"
    },
    {
      "trait_type": "ABILITY",
      "value": "TRANSPLANAR GLIDE"
    },
    {
      "trait_type": "RARITY",
      "value": "ULTRA"
    }
  ],
  "properties": {
    "files": [
      {
        "uri": "https://arweave.net/32M4ARiDKDwjLfukYKC378O6FPeWnXnpHh9G2oSpI20",
        "type": "image/png"
      },
      {
        "uri": "https://arweave.net/yLCKZAAO4GgHhJ8ShhtCpc0g0cVwrBdA3mz7r5enVC8",
        "type": "video/mp4"
      }
    ]
  }
}
```

### Priority this issue should have

Medium (should be fixed soon)

**Comment by samuelvanderwaal** [comment]
@nypam What is the "proper extension" for images and animations and where is this defined? I'm not seeing anything definitive in the Arweave docs I've looked at.

Also, which wallets don't display the images and videos correctly?

[This seems to work](https://github.com/metaplex-foundation/sugar/pull/325), but I'm not sure if that's the official way to do it so don't want to merge it until I get something more definitive.

**Comment by what-name** [comment]
facing the same issue. `sugar launch` uploads all the files etc. but the video does not work in wallets, nor in explorers. Eg. a CM deployed with Sugar does not work for videos.

example: https://solscan.io/token/9fk9rBxSbkf4a79tEc2VCykFbHBMTGxS2gfvmZeM9ZKp?cluster=devnet#metadata

**Comment by samuelvanderwaal** [comment]
> facing the same issue. `sugar launch` uploads all the files etc. but the video does not work in wallets, nor in explorers. Eg. a CM deployed with Sugar does not work for videos.
> 
> example: https://solscan.io/token/9fk9rBxSbkf4a79tEc2VCykFbHBMTGxS2gfvmZeM9ZKp?cluster=devnet#metadata

I'm not sure that this is an Arweave link extension issue because if you just open the Arweave link in a browser the video plays: https://x33yutmlk43lqnodwoxyzsmguuj4ethd5r2ez57bsfdq7meurmbq.arweave.net/vveKTYtXNrg1w7OvjMmGpRPCTOPsdEz34ZFHD7CUiwM

**Comment by nypam** [comment]
The way I fix the issue on my end.

1. I run sugar upload
2. I edit cache.json and add the **?ext=gif** and **?ext=mp4** to **image_link** and **animation_link**
3. In cache.json I remove the value of **metadata_link** and **metadata_hash**
4. I run sugar upload once again and the extensions are correctly appended to the metadata.

Example of file: https://solscan.io/token/3g61bajrL8iEGZuotKwibaczgfBhauxzeFVRuSpkMfNE#metadata

**Comment by samuelvanderwaal** [comment]
> The way I fix the issue on my end.
> 
> 1. Run `sugar upload`
> 2. Edit **cache.json** and add the **?ext=gif** and **?ext=mp4** to **image_link** and **animation_link**
> 3. Edit **cache.json** and remove the value of **metadata_link** and **metadata_hash**
> 4. Run `sugar upload` again, and the extensions will be appended to the metadata.
> 
> Example of file: https://solscan.io/token/3g61bajrL8iEGZuotKwibaczgfBhauxzeFVRuSpkMfNE#metadata

This is very helpful, thanks. I'll get a PR fix up for it today.
