### ISSUE TITLE
[Feature]: Allow mixing of filetypes

### ISSUE THREAD

**Issue by MarkSackerberg** [metaplex-foundation/sugar#306]
### Feature

not sure if it is a new feature or more a kind of bug:

In the discord we see ones in a while projects that want to mix for example gifs and pngs (e.g https://discord.com/channels/848060988636921856/964232640150528071/1004554530626748508 ). This does currently not work, sugar throws an “invalid file extension” error instead.

same issue and this is **more important** from my point of view: you can also not use a png as collection image if the other images are gifs (and other way around obviously) e.g. https://discord.com/channels/848060988636921856/964232640150528071/1004744176170193016

### Ideal solution or implementation

Allow mixing different image (and animation?) filetypes by not just looking at the first detected filetype, but instead checking each for each index of it is a valid filetype

### Alternative solutions or implementations

Handle collection files independently so that at least those assets can be of a different type

**Comment by stranzhay** [comment]
This is supported now to a certain extent. i.e. 0.png 0.gif, 1.png, 2.png 2.gif.  You are saying it should be like 0.png, 1.gif, 2.png, 3.gif  @MarkSackerberg

**Comment by MarkSackerberg** [comment]
Exactly. This is a requirement multiple people asked for in discord in the last days.
From my point of view we should at least allow to have
collection.png 0.gif 1.gif etc.

**Comment by KartikSoneji** [comment]
Personally, I think the `<number>.<extension>` format is needlessly complex and usually leads to issues.
Using the json number might lead to less confusion.

**Comment by MarkSackerberg** [comment]
> Personally, I think the `<number>.<extension>` format is needlessly complex and usually leads to issues.
> Using the json number might lead to less confusion.

Which is what I was (trying) to propose.
0.json should be able to have 0.png 0.gif 0.mp4 
1.json should be able to have 1.png 1.gif 1.mp4
Same for collection.json collection.png collection.gif collection.mp4

**Comment by KartikSoneji** [comment]
I was actually thinkning `0.json` supports `image.(png | gif)` in image, and `<anything>.(mp4 | html | glb | mp3)` in animation.
That way, if the respective field is not a valid url, upload `<json number>.(png | jpg | jpeg)` or `<json number>.(mp4 | html | glb | mp3)` in that order.
Warn if a file doesn't match or more than one matches.

**Comment by wooddyy-sol** [comment]
just opened a PR for this. #427 .

in case it doesn't get approved, that's how you can achieve it.

**Comment by wooddyy-sol** [comment]
This should be available now in [v2.0.0-beta.2](https://github.com/metaplex-foundation/sugar/releases/tag/v2.0.0-beta.2)

**Comment by samuelvanderwaal** [comment]
Closed by #427, thanks @wooddyy-sol!
