### ISSUE TITLE
error sending request for url (http://localhost:8899/): error trying to connect: tcp connect error: Connection refused (os error 61)

### ISSUE THREAD

**Issue by LELUK911** [metaplex-foundation/sugar#365]
Hi guys,

I following tutorial on metaplex documentations, but when i try upload, terminal returne me this error:
`[1/4] 🗂  Loading assets
Found 10 asset pair(s), uploading files:
+--------------------+
| images    |     10 |
| metadata  |     10 |
+--------------------+

[2/4] 🖥  Initializing upload

🛑 Error running command (re-run needed): error sending request for url (http://localhost:8899/): error trying to connect: tcp connect error: Connection refused (os error 61)
`
this is configuration file:

`{
  "price": 1000.0,
  "number": 10,
  "gatekeeper": null,
  "creators": [
    {
      "address": "9***********************************K",
      "share": 100
    }
  ],
  "solTreasuryAccount": "9***************************K",
  "splTokenAccount": null,
  "splToken": null,
  "goLiveDate": "2022-09-25T04:10:29.072976+00:00",
  "endSettings": null,
  "whitelistMintSettings": null,
  "hiddenSettings": null,
  "freezeTime": null,
  "uploadMethod": "bundlr",
  "retainAuthority": true,
  "isMutable": true,
  "symbol": "CRAB",
  "sellerFeeBasisPoints": 500,
  "awsConfig": null,
  "nftStorageAuthToken": null,
  "shdwStorageAccount": null
}
`

any cam help me ?

**Comment by KartikSoneji** [comment]
You have to specify the rpc url as devnet or mainnet.
Run:
```sh
# for mainnet:
solana config set --url mainnet-beta

# for mainnet
solana config set --url devnet
```

**Comment by LELUK911** [comment]
Perfect! now work! 
I thought that i must set "devent" in sugar command.. but Ok very Thnk

**Comment by KartikSoneji** [comment]
Great to hear it's working now.
In the future, please try to use the discord channel for help unless you feel there is a bug in sugar itself.
Also, can you please close the issue to avoid confusion.
