### ISSUE TITLE
x image associations for xxxx numbers of json

### ISSUE THREAD

**Issue by tolgaand** [metaplex-foundation/sugar#371]
Hello,
I want to create a collection of NFT whose images are identical to each other, this library does not allow this.

What should I do for this?

**Comment by samuelvanderwaal** [comment]
Check out the [Hidden Settings](https://docs.metaplex.com/developer-tools/sugar/learning/settings#hidden-settings) feature. Alternately, you can just upload a single asset pair and then copy the links to be the same.

**Comment by tolgaand** [comment]
> Check out the [Hidden Settings](https://docs.metaplex.com/developer-tools/sugar/learning/settings#hidden-settings) feature. Alternately, you can just upload a single asset pair and then copy the links to be the same.

I tried to do it with Hidden Settings, but it failed.
I guess there is no way for me to upload jsons and images independently.
<img width="280" alt="Screen Shot 2022-09-29 at 10 41 07" src="https://user-images.githubusercontent.com/26303690/192970445-e989bda9-9a91-41a0-ae04-421ea9a929cb.png">

thanks for your comment

**Comment by ohaddahan** [comment]
> Hello, I want to create a collection of NFT whose images are identical to each other, this library does not allow this.
> 
> What should I do for this?

Simplest way is just to duplicate the images, not efficient but works.

**Comment by tolgaand** [comment]
> > Hello, I want to create a collection of NFT whose images are identical to each other, this library does not allow this.
> > What should I do for this?
> 
> Simplest way is just to duplicate the images, not efficient but works.

Reloading duplicate images is costly. So I have 4 different images uploaded to airweave, I can't add them to the metadata because "sugar" wants the number of json and the number of images to be equal..

**Comment by samuelvanderwaal** [comment]
Are the attributes of the NFTs the same as well, or just the images?

**Comment by tolgaand** [comment]
> Are the attributes of the NFTs the same as well, or just the images?

the attributes are different, the images(4 different images) the same
