### ISSUE TITLE
[Bug]: Run validate before upload

### ISSUE THREAD

**Issue by KartikSoneji** [metaplex-foundation/sugar#374]
### Issue description

1. Create invalid json
2. Run `sugar upload`
3. Invalid json is uploaded successfully

Most users don't run `sugar validate`, so it should be run automatically before the upload command.

### Priority this issue should have

Medium (should be fixed soon)

**Comment by samuelvanderwaal** [comment]
I think keeping `validate` gives users more flexibility if they want to upload non-standard JSON files. There's always a trade-off between protecting users every step of the way and adding as much convenience as possible and having flexibility. I think we're currently on the right side of the trade off for this but am open to other thoughts.
