### ISSUE TITLE
[Bug]: Sugar Reveal gives an error running command.

### ISSUE THREAD

**Issue by Koni20021** [metaplex-foundation/sugar#388]
### Issue description

It gives an error when I run **Sugar Reveal** @samuelvanderwaal 

### Relevant log output

![Screenshot 2022-10-08 124334](https://user-images.githubusercontent.com/115045669/194724733-a8e93e18-8f1e-46ab-ac02-31626f7462de.png)

### Priority this issue should have

High (immediate attention needed)

**Comment by samuelvanderwaal** [comment]
> ### Issue description
> It gives an error when I run **Sugar Reveal** @samuelvanderwaal
> 
> ### Relevant log output
> ![Screenshot 2022-10-08 124334](https://user-images.githubusercontent.com/115045669/194724733-a8e93e18-8f1e-46ab-ac02-31626f7462de.png)
> 
> ### Priority this issue should have
> High (immediate attention needed)

Reveal is a very heavy command that requires a [custom RPC](https://docs.metaplex.com/resources/rpc-providers). It's not going to work on the public default ones.

**Comment by Koni20021** [comment]
But I am testing it on devnet shouldn't it work their ofcourse for launching the collection I'll use a cutom mainnet rpc but before I have to test that all works perfectly.

**Comment by samuelvanderwaal** [comment]
> @samuelvanderwaal But I am testing it on devnet shouldn't it work their ofcourse for launching the collection I'll use a cutom mainnet rpc but before I have to test that all works perfectly.

Try using QuickNode's free devnet node and see if it works with that. If not, we may need to allow setting a longer timeout in Sugar.

**Comment by Koni20021** [comment]
> > @samuelvanderwaal But I am testing it on devnet shouldn't it work their ofcourse for launching the collection I'll use a cutom mainnet rpc but before I have to test that all works perfectly.
> 
> Try using QuickNode's free devnet node and see if it works with that. If not, we may need to allow setting a longer timeout in Sugar.

I'll try it and get back to you but can you add -t (timeout) option also in sugar reveal though I have a big collection of 6000 NFTs. But I am testing only with 10 NFTs and it still gives error I'll try to it with quicknodes devnet rpc and get back to you ASAP.

**Comment by Koni20021** [comment]
![error](https://user-images.githubusercontent.com/115045669/194754008-3a3bcc76-22be-4866-bbae-0ceaab1959f0.png)

bro, it still didn't work. I used a custom devnet rpc also

**Comment by Koni20021** [comment]
used quicknodes devnet rpc and it worked so closing the issue thanks.
