### ISSUE TITLE
[Feature]: Add Timeout -t option for sugar reveal [OPTIONS]

### ISSUE THREAD

**Issue by Koni20021** [metaplex-foundation/sugar#390]
### Feature

Revealing is a heavy-duty command adding a timeout option will help immensely.

### Ideal solution or implementation

For suppose I have a  collection of 10000 NFT this command will give timeout error again and again but if a timeout or a cooldown option is added we can set it and watch our NFTs getting revealed.

**Comment by crazyrick4** [comment]
Hey, not sure when the `--timeout` function was added but it exists in `sugar-cli 1.1.2-alpha+CMv3`
(all the way at the bottom of the screenshot)
![image](https://user-images.githubusercontent.com/100683095/212685528-27e03a8b-48b3-4f0e-a170-25e4297290f6.png)
