### ISSUE TITLE
Hidden settings with number as 0 not working?

### ISSUE THREAD

**Issue by bilaljawed** [metaplex-foundation/sugar#396]
Hi guys,

I'm under the impression by reading everywhere that I'm supposed to keep number (supply) as 0 when using hidden settings, but it throws me an error:

`Number of items (0) do not match cache items (10)`

However when I upload with 10 number it uploads, and I can change the number of supply later on to whatever number I want. So if the collection is on reveal and metadata is not ready, what should go in the hash?

**Comment by febo** [comment]
Ideally you will have all assets uploaded when you create the candy machine with hidden settings. If they are not, you can create the candy machine with the current hash and update the hash value afterwards using the `update` command.
