### ISSUE TITLE
error when running sugar with NanoX very frustrating!

### ISSUE THREAD

**Issue by puppetofsmut** [metaplex-foundation/sugar#401]
I Keep getting this error kwhen trying to run sugar ive had no problems in the past but doing it with a hardware wallet dousnt seem to work?
✔ What is the price of each NFT? · .11
✔ Found 4 file pairs in "assets". Is this how many NFTs you will have in your candy machine? · yes
✔ Found symbol "SBL" in your metadata file. Is this value correct? · yes
✔ Found value 250 for seller fee basis points in your metadata file. Is this value correct? · yes
? What is your go live date? Many common formats are supported. If unsure, try YYYY-MM-DD HH:MM:SS [+/-]UTC-OFFSET or ty✔ What is your go live date? Many common formats are supported. If unsure, try YYYY-MM-DD HH:MM:SS [+/-]UTC-OFFSET or type 'now' for current time. For example 2022-05-02 18:00:00 +0000 for May 2, 2022 18:00:00 UTC. · now
✔ How many creator wallets do you have? (max limit of 4) · 1
✔ Enter creator wallet address #1 · ✔ What is the price of each NFT? · .11
✔ Found 4 file pairs in "assets". Is this how many NFTs you will have in your candy machine? · yes
✔ Found symbol "SBL" in your metadata file. Is this value correct? · yes
✔ Found value 250 for seller fee basis points in your metadata file. Is this value correct? · yes
? What is your go live date? Many common formats are supported. If unsure, try YYYY-MM-DD HH:MM:SS [+/-]UTC-OFFSET or ty✔ What is your go live date? Many common formats are supported. If unsure, try YYYY-MM-DD HH:MM:SS [+/-]UTC-OFFSET or type 'now' for current time. For example 2022-05-02 18:00:00 +0000 for May 2, 2022 18:00:00 UTC. · now
✔ How many creator wallets do you have? (max limit of 4) · 1
✔ Enter creator wallet address #1 · wieirtdx2jxUe5h6EJqaU6U7QA8zTMQcPCBek9dR6oGhCb
✔ Enter royalty percentage share for creator #1 (e.g., 70). Total shares must add to 100. · 100
✔ Which extra features do you want to use? (use [SPACEBAR] to select options you want and hit [ENTER] when done) ·

Error running command (re-run needed): Failed to read keypair file: usb://ledger/wiert2jxUe5h6EJqaU6U7QA8zTMQcPCBek9dR6oGhCb?key=0'/0', The filename, directory name, or volume label syntax is incorrect. (os error 123)
✔ Enter royalty percentage share for creator #1 (e.g., 70). Total shares must add to 100. · 100
✔ Which extra features do you want to use? (use [SPACEBAR] to select options you want and hit [ENTER] when done) ·

Error running command (re-run needed): Failed to read keypair file: usb://ledger/CSGrqx2jxUe5h6EJqaU6U7QA8zTMQcPCBek9dR6oGhCb?key=0'/0', The filename, directory name, or volume label syntax is incorrect. (os error 123)

**Comment by samuelvanderwaal** [comment]
Sugar doesn't currently have support for hardware wallets, so this is not expected to work.
