### ISSUE TITLE
[Bug]: maxEditionSupply parameter is ignored

### ISSUE THREAD

**Issue by GabrielePicco** [metaplex-foundation/sugar#404]
### Issue description

Steps to reproduce:

- set "maxEditionSupply": 100 in the config.json
- `sugar launch`
- `sugar mint`

In the metadata of the minted token the maxSupply is set to 0

### Priority this issue should have

Medium (should be fixed soon)

**Comment by samuelvanderwaal** [comment]
`maxEditionSupply` isn't a [valid config value](https://docs.metaplex.com/developer-tools/sugar/reference/configuration). It's probably something we could add, but it seems a bit of a strange use-case to use a candy machine to create master editions with print supplies. Can you elaborate on your use case?

**Comment by GabrielePicco** [comment]
Thanks @samuelvanderwaal , I wasn't looking at the right part of the documentation. In our use-case we just wanted to have a CandyMachine with master editions that users could print up to a maximum number of times, not sure how common it is tough. I modified [this line](https://github.com/metaplex-foundation/sugar/blob/main/src/deploy/initialize.rs#L86) to achieve it for now. I can open a PR to add it to the config if you think is useful.
