### ISSUE TITLE
[Bug]: Sugar Reveal - error sending request

### ISSUE THREAD

**Issue by syrafs** [metaplex-foundation/sugar#407]
### Issue description

1. Setup a candy machine with hidden settings
2. Here are my settings from config:

`  "hiddenSettings": {
    "name": "GamersKing V1 Hidden",
    "uri": "https://nftstorage.link/ipfs/bafybeibfgqprswlo73j6f74lsb2abzmo577576wkw35gwxmqa4iyliqt4i/0.json",
    "hash": "Hd5AjjJbxfpXA2qUey1z8AUMsGJPTfJU"
  },`
3. Not sure if it is an RPC issue but everything else is fine except for 'sugar reveal'

### Relevant log output

```shell
$ sugar reveal
[1/4] Loading items from the cache
▪▪▪▪▪ Done

[2/4] Getting minted NFTs for candy machine FKnR3G7tfpdJDSH4dLvwbHT6Zmut5kr5rmLnR7Mcfc5N

Error running command (re-run needed): error sending request for url (https://api.devnet.solana.com/): operation timed out
```

### Priority this issue should have

High (immediate attention needed)

**Comment by samuelvanderwaal** [comment]
The reveal command does not work with the default public RPC node, you will need a private node that supports gPA calls on Token Metadata: https://docs.metaplex.com/resources/rpc-providers.

**Comment by syrafs** [comment]
Hmm, that is weird because I was finally abled to do 'sugar reveal' yesterday and it worked using Alchemy but now it is not working anymore.

`Error running command (re-run needed): error sending request for url (https://solana-devnet.g.alchemy.com/v2/RPBj-7oUhtcgGL_o6PneNMK7TV1CxxY): operation timed out`

**Comment by samuelvanderwaal** [comment]
> Hmm, that is weird because I was finally abled to do 'sugar reveal' yesterday and it worked using Alchemy but now it is not working anymore.
> 
> `Error running command (re-run needed): error sending request for url (https://solana-devnet.g.alchemy.com/v2/RPBj-7oUhtcgGL_o6PneNMK7TV1CxxY): operation timed out`

What version of Sugar? 

```
sugar -V
```

**Comment by syrafs** [comment]
```
$ sugar --version
sugar-cli 1.1.0
```

1.10 is my Sugar version

**Comment by samuelvanderwaal** [comment]
> ```
> $ sugar --version
> sugar-cli 1.1.0
> ```
> 
> 1.10 is my Sugar version

Try updating to v1.2 and seeing if it works.

**Comment by syrafs** [comment]
Yep it works now, thanks!
