### ISSUE TITLE
[Bug]: AWS storage - Config not found

### ISSUE THREAD

**Issue by czareko** [metaplex-foundation/sugar#409]
### Issue description

Sugar version 1.2.0
1. Select AWS during (sugar create-config)
2. Set bucket name (public with full access available)
3. profile - default
5. catalog - root
6. AWS domain - default
All other steps default
Execute: sugar upload

The same configuration with Bundlr or NFTStorage, works without any problems on DevNet and MainNet

### Relevant log output

```shell
[1/4] 🗂  Loading assets
Found 1 asset pair(s), uploading files:
+--------------------+
| images    |      1 |
| metadata  |      1 |
+--------------------+

[2/4] 🖥  Initializing upload

🛑 Error running command (re-run needed): Config not found
```

### Priority this issue should have

Medium (should be fixed soon)

**Comment by samuelvanderwaal** [comment]
Do you have an AWS credentials file at `$HOME/.aws/credentials`? In case you haven't seen the docs for this section yet make sure you're following the procedure [here](https://docs.metaplex.com/developer-tools/sugar/reference/upload-methods#amazon-aws-s3).

**Comment by czareko** [comment]
@samuelvanderwaal You are right. I verified everything and it works.
