### ISSUE TITLE
[Bug]: Upload error: Response failed with the following error: Status: 402 Payment Required

### ISSUE THREAD

**Issue by czareko** [metaplex-foundation/sugar#410]
### Issue description

Standard configuration, with two creator wallets and upload to Bundlr
On the mainnet, I tried with:
https://rpc.ankr.com/solana
https://api.mainnet-beta.solana.com/
https://solana-mainnet.g.alchemy.com/v2/[MY_UNIQUE_ID]
Results are always the same.
Around two weeks ago I was uploading the same configuration to the mainnet and it was working without any problems.
Sugar versions: 1.0 and 1.2

### Relevant log output

```shell
[1/4] 🗂  Loading assets
Found 3 asset pair(s), uploading files:
+--------------------+
| images    |      0 |
| metadata  |      3 |
+--------------------+

[2/4] 🖥  Initializing upload
▪▪▪▪▪ Connected
Funding address:
  -> pubkey: HxzqvBiDXABaTLGNQ4uhPoRvHUHZtA1x1sRU7UPca2vz
  -> lamports: 5977 (◎ 0.000005977)
Signature: 5iKXNwxYbvFUdmqpXpQhtUrNww5wfAg4EArpVgcF9sCQGxnzuzvoDCqUCGfPgSS8UiWjM7pqM4wQmvoEuGfPLht3

[3/4] 📤 Uploading image files (skipping)

[4/4] 📤 Uploading metadata files 

Sending data: (Ctrl+C to abort)
[00:00:01] Upload failed ██████████████████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 1/3

1/3 asset pair(s) uploaded.

🛑 Error running command (re-run needed): Failed to upload all files, 2 error(s) occurred:
=> Upload error: Response failed with the following error: Status: 402 Payment Required
```

### Priority this issue should have

High (immediate attention needed)

**Comment by samuelvanderwaal** [comment]
Looks like your Pubkey has enough funds so not sure why you're getting this error. I'll ask Bundlr if they have any ideas.

**Comment by samuelvanderwaal** [comment]
This should work now so please try it again and let me know. We'll be releasing a Sugar patch version this week (1.2.1) which will be forward compatible with a change Bundlr is making for this soon, so make sure to update once it's out.

**Comment by raggi-eth** [comment]
hey samuel, im having the same issue 

solana balance
0.350526761 SOL

Funding address:
  -> pubkey: devSFRZdCWWJh5Nyh6KaDiDxUxQnnwotJqdpK1cNppU
  -> lamports: 10513 (◎ 0.000010513)

🛑 Error running command (re-run needed): unable to confirm transaction. This can happen in situations such as transaction expiration and insufficient fee-payer funds

**Comment by raggi-eth** [comment]
after re-running im seeing 
Funding address:
  -> pubkey: devSFRZdCWWJh5Nyh6KaDiDxUxQnnwotJqdpK1cNppU
  -> lamports: 16239 (◎ 0.000016239)
Signature: 4G7JwpyXaJDz1iJ4RP4tXWAb9yc7f4MXDwd8T1xGkFfohWnw7yg3Ds8ai9MgP8G8U6hGu6adC9FBhyW6Cbd7Q4r4

🛑 Error running command (re-run needed): No Bundlr balance found for address: devSFRZdCWWJh5Nyh6KaDiDxUxQnnwotJqdpK1cNppU, check Bundlr cluster and address balance

**Comment by czareko** [comment]
For me, it works now. I think it was some external problem. I even didn't have to update the sugar version.
It would be good to have better logs, to find who is exactly responsible for the problem.

**Comment by vmrodrigues** [comment]
Hi All. I also have the same issue here. 
[2/4] 🖥  Initializing upload
▪▪▪▪▪ Connected
Funding address:
  -> pubkey: DHA6WnrsJ74Q4fWT7AjwUcz1XmVVghPHrVdT5uZ9t8c2
  -> lamports: 187995 (◎ 0.000187995)
Signature: 4sGyf4UZM2e7xoy3FdvWpcuxmBKUyB8nFfN9Eh8As3WGUEfEP9HWiYPKLkfiQ3s6CaPYc1VJAkAqjZGNYVEM8w7X

[3/4] 📤 Uploading image files (skipping)
[4/4] 📤 Uploading metadata files 

Sending data: (Ctrl+C to abort)
[00:00:01] Upload failed █████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 16/101

16/101 asset pair(s) uploaded.

🛑 Error running command (re-run needed): Failed to upload all files, 85 error(s) occurred:
=> Upload error: Response failed with the following error: Status: 402 Payment Required

> solana balance    
9.139452438 SOL

**Comment by samuelvanderwaal** [comment]
> Hi All. I also have the same issue here. [2/4] 🖥 Initializing upload ▪▪▪▪▪ Connected Funding address: -> pubkey: DHA6WnrsJ74Q4fWT7AjwUcz1XmVVghPHrVdT5uZ9t8c2 -> lamports: 187995 (◎ 0.000187995) Signature: 4sGyf4UZM2e7xoy3FdvWpcuxmBKUyB8nFfN9Eh8As3WGUEfEP9HWiYPKLkfiQ3s6CaPYc1VJAkAqjZGNYVEM8w7X
> 
> [3/4] 📤 Uploading image files (skipping) [4/4] 📤 Uploading metadata files
> 
> Sending data: (Ctrl+C to abort) [00:00:01] Upload failed █████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 16/101
> 
> 16/101 asset pair(s) uploaded.
> 
> 🛑 Error running command (re-run needed): Failed to upload all files, 85 error(s) occurred: => Upload error: Response failed with the following error: Status: 402 Payment Required
> 
> > solana balance
> > 9.139452438 SOL

Update to the latest version of Sugar.

**Comment by lucas122478** [comment]
> > For me, it works now. I think it was some external problem. I even didn't have to update the sugar version. It would be good to have better logs, to find who is exactly responsible for the problem.
> 
> They reverted back the change but it will get updated soon, so make sure you're on the latest version of sugar to avoid the issue in the future.

Could you guys update the sugar-alphaCMv3 executable to reflect whatever the bundlr issue is? Getting it continously on this version of sugar-cli too.
