### ISSUE TITLE
[Bug]: Error: Transaction too large: 1257 > 1232 (2 Guards)

### ISSUE THREAD

**Issue by syrafs** [metaplex-foundation/sugar#411]
### Issue description

I got the error when trying to send a transaction to mint using two guards. Is there a way to bypass this?

Minting code:
`const { nft } = await metaplex.candyMachines().mint({
    candyMachine,
    collectionUpdateAuthority: collectionUpdateAuthority,
    owner: FROM_KEYPAIR.publicKey,

    // settings: {
    //     thirdPartySigner: { signer: thirdPartySigner },
    // },
    guards: {
      nftBurn: {
        mint: new PublicKey("7RbMGu5R1vr44PVuUopxgM8v1ugWBSJLU8BasPUopsto"),
      },
    },
  });`

My guard settings:
`"guards": {
    "default": {
      "nftBurn": {
        "requiredCollection": "HFQcayh1UyBsu565tWWq3UUAjfGBA4Pi7Pqs7rX5qNR7"
      },
      "tokenBurn": {
        "amount": 5000,
        "mint": "GowW4G6qXsaUTgnGJr3bHBCYSZqWUvGbNwCBaMY4Av3X"
      }
    }
  }`

Throws error:
`    throw new Error(message || 'Assertion failed');
          ^

Error: Transaction too large: 1257 > 1232`

My sugar version is: sugar-cli 1.1.2-alpha+CMv3

### Priority this issue should have

High (immediate attention needed)

**Comment by febo** [comment]
This is a limitation of the transaction size. You will need to use a versioned transaction in this scenario: https://docs.solana.com/developing/versioned-transactions

**Comment by syrafs** [comment]
So I’ll need to add this instruction under the tx instructions and send them via versioned txn? 

How do I send a signed instruction with the metaplex sdk though?
