### ISSUE TITLE
[Bug]: Sugar sign does not work with ledger wallet

### ISSUE THREAD

**Issue by Cptn-Haddock** [metaplex-foundation/sugar#416]
### Issue description

Steps to reproduce (on windows machine):

    sugar sign usb://ledger?key=0

Response:

    Failed to read keypair file: usb://ledger?key=0, The filename, directory name, or volume label syntax is incorrect. (os error 123)

### Relevant log output

```shell
🛑 Error running command (re-run needed): Failed to read keypair file: usb://ledger?key=0, The filename, directory name, or volume label syntax is incorrect. (os error 123)
```

### Priority this issue should have

Medium (should be fixed soon)

**Comment by samuelvanderwaal** [comment]
Sugar does not have Ledger support at this time.

**Comment by arkitoure** [comment]
Hello @samuelvanderwaal, any ETA on when Ledger will be supported?

Also, I would suggest that this be prominently featured in Metaplex>Candy Machine>Sugar documentation, if not already, for those of us lost on this issue.

And lastly, our team used a Ledger based account to grant main creator status to an NFT collection recently. Now of course we are not able to sign it due to this issue. What would best practice be to change the primary creator?

**Comment by samuelvanderwaal** [comment]
> Hello @samuelvanderwaal, any ETA on when Ledger will be supported?
> 
> Also, I would suggest that this be prominently featured in Metaplex>Candy Machine>Sugar documentation, if not already, for those of us lost on the issue.
> 
> And lastly, our team used a Ledger based account to grant main creator status to an NFT collection recently. Now of course we are not able to sign it due to this issue. What would best practice be to change the primary creator?

There are no current plans to support this feature as using a Ledger wallet to sign dozens or hundreds of transactions by manually clicking the buttons isn't really a feasible option. It's possible we could use a derived keypair as a work around, or automatically change the update authority behind the scenes but I don't know when the team will have time to investigate this. 

You can open a feature request for this, though, so it's in the list of things the community wants improved.

**Comment by arkitoure** [comment]
Hi @samuelvanderwaal , thank you for the follow up.

Agreed on that point, yet for certain applications with fairly low signings this feature might be imperative. For instance, NFT association to high value physical items. In such a case, hot wallet usage might be an undesirable option. We are faced with something like this right now so its a hot topic atm.

Im foggy on this but when deploying a new collection via Sugar, sans minting, would this require signing each individual NFT or just single actions–validate, upload, deploy, verify?

Side note...Solved the primary creator issue with your Metaboss tool, kudos for that life saver!
