### ISSUE TITLE
[Bug]: Install error when installing cmv3 alpha 3 with crate

### ISSUE THREAD

**Issue by alexajwhite** [metaplex-foundation/sugar#417]
### Issue description

Error appears when trying to install the package from source using crate issue appears to be with the imported guard file.

### Relevant log output

```shell
error[E0063]: missing field `allocation` in initializer of `mpl_candy_guard::guards::GuardSet`
   --> src/config/guard_data.rs:203:12
    |
203 |         Ok(mpl_candy_guard::guards::GuardSet {
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing `allocation`
```

### Priority this issue should have

Medium (should be fixed soon)

**Comment by samuelvanderwaal** [comment]
@alexajwhite Is this issue still present?
