### ISSUE TITLE
[Bug]: Token delegate remains after frozen NFTs are thawed

### ISSUE THREAD

**Issue by DeepGreenAI** [metaplex-foundation/sugar#418]
### Issue description

Steps to reproduce:

1. Use sugar to Launch a candy machine v2 with freeze function enabled.
2. Wait for freezeTime to elapse and then use sugar thaw --all to thaw all frozen NFTs.
3. The thawed NFTs will still have a token delegate which is causing issues in some staking contracts.

The token delegate should be removed when the NFT is thawed if possible. Here is an example NFT that was minted that still has a token delegate.

**NFT token address**: 5amipwGeRre846raWLSs6QqpN99KKh6HxgcV8sCAkbhT
**Token delegate for above NFT:** 84FVX6CkVpWRPjZfsmwf1JeeHsSajpnYjLDdoaA5LRzP

Let me know if you have any questions on the above or if you think that this is a feature and not a bug. Thank you!

### Priority this issue should have

Medium (should be fixed soon)

**Comment by samuelvanderwaal** [comment]
It [tries to revoke the SPL token delegate](https://github.com/metaplex-foundation/metaplex-program-library/blob/f5a94fae0f7fa397cde6fc08435bb6a79de8c350/candy-machine/program/src/processor/freeze/thaw_nft.rs#L103), but only the owner can do it, so if you're signing as the update authority to do the thaw it can't revoke for you and owners will either need to call `thaw` on their own token or to run revoke themselves.

**Comment by samuelvanderwaal** [comment]
The other thing users can do is just transfer the NFT between two of their wallets as the delegate exists on the token account and so will be cleared with the token is transferred to a new token account.
