### ISSUE TITLE
[Bug]: Sugar Reveal - No captures found

### ISSUE THREAD

**Issue by crazyrick4** [metaplex-foundation/sugar#419]
### Issue description

Hey, when trying to use the `sugar reveal` command on version 1.1.2-alpha+CMv3.
I get the following error: (see code)

No captures found for [Collection name], I'm unsure on what went wrong and where. Couldn't find any info anywhere on the internet as of posting this bug report.

### Relevant log output

```shell
[1/4] Loading items from the cache
▪▪▪▪▪ Done

[2/4] Getting minted NFTs for candy machine [CM hidden for privacy]
▪▪▪▪▪ Found xxxx accounts

[3/4] Matching NFTs to cache values
▪▪▪▪▪ Done

[4/4] Updating NFT URIs from cache values

Error running command (re-run needed): No captures found for [Collection name hidden for privacy]
```

### Priority this issue should have

High (immediate attention needed)

**Comment by samuelvanderwaal** [comment]
The way reveal works is that it matches the NFT number by parsing it from the name and then matches it to the number in the cache file and updates the URI to the one stored in the cache file. If your NFTs have a non-standard naming scheme Sugar's `reveal` may not work and you might have to do the reveal yourself using your own script or a tool like Metaboss with a file that maps what NFT should get what new URI.

The error comes from [here](https://github.com/metaplex-foundation/sugar/blob/a965a540e56096d22360fef5c3f72ade7e4edec9/src/reveal/process.rs#L197) where it's trying to parse out the number from the collection name.

**Comment by crazyrick4** [comment]
Alright thanks @samuelvanderwaal do you happen to know if Metaboss' CMv2 function works the same as CMv3? I believe it does, but would like it confirmed if you could. Thanks - after I'll close the bug report

**Comment by samuelvanderwaal** [comment]
> Alright thanks @samuelvanderwaal do you happen to know if Metaboss' CMv2 function works the same as CMv3? I believe it does, but would like it confirmed if you could. Thanks - after I'll close the bug report

I'm not sure what you mean when you say Metaboss' CMv2 function. What specific command are you referring to?

**Comment by crazyrick4** [comment]
For example with the `snapshot` function.

For reference see:
![image](https://user-images.githubusercontent.com/100683095/213117378-bd80caf0-fdae-400c-a461-66c6f8926b3b.png)

**Comment by cesar4design** [comment]
I have the same issue, i think my nft names are correct¿?

![image](https://github.com/metaplex-foundation/sugar/assets/75784005/c2ddd174-d94b-4864-8c9e-675cc2493abb)
