### ISSUE TITLE
[Feature]: How can we use number as attribute value?

### ISSUE THREAD

**Issue by legendaryangelist** [metaplex-foundation/sugar#425]
### Feature

Can we use number as attribute value?
In current version, only string value is allowed for nft attribute value.

### Ideal solution or implementation

I think it would be nice if we can use number type for attribute value as well as string type.

**Comment by wooddyy-sol** [comment]
out of curiosity, what is the use case?

You could just use something like `'1'`. 

I can't think of a reason where you might need a number Type.

**Comment by samuelvanderwaal** [comment]
Closing for lack of response. I think string numbers are fine, but this can be re-opened for discussion if there's some clear use-case that string numbers don't support.
