### ISSUE TITLE
[Feature]: Allow multiple nftPayments / nftBurns per mint.

### ISSUE THREAD

**Issue by abrozzesi** [metaplex-foundation/sugar#434]
### Feature

Allow multiple nftPayments / nftBurns per mint.

### Ideal solution or implementation

Simple solution is to extend the gate to allow an `amount` as a part of the configuration. Then during the mint process it simply burns multiple at once

**Comment by samuelvanderwaal** [comment]
This is more of a feature request for the [Candy Guard ](https://github.com/metaplex-foundation/mpl-candy-guard)contract itself, correct?

**Comment by abrozzesi** [comment]
True, I will raise there. May be worth leaving this open though as a small change would need to be made to sugar as well to accommodate the new feature.

Up to you.

**Comment by samuelvanderwaal** [comment]
If a Candy Guard change is made Sugar can be updated, but I don't think this issue needs to stay open.
