### ISSUE TITLE
[Feature]: Account compression

### ISSUE THREAD

**Issue by katopz** [metaplex-foundation/sugar#437]
### Feature

I'm not sure that we support Account compression or not?

### Ideal solution or implementation

Should be some parameter or flag to enabled compress or not compress feature.

**Comment by samuelvanderwaal** [comment]
Candy Machine itself doesn't support account compression so this isn't really a direct Sugar issue. I don't think Candy Machine will be updated in the near-term to support compression but you can open an issue there if you wish, I will close this for now.
