### ISSUE TITLE
[Feature]: sugar-cli 2.1.1 it does not perform the step sugar deploy

### ISSUE THREAD

**Issue by luisrovirac** [metaplex-foundation/sugar#442]
### Issue description

When creating a Candy Machine with sugar-cli 2.1.1 it does not perform the step sugar deploy, Error running command (re-run needed): Missing collection item in cache

### Relevant log output

```shell
Error running command (re-run needed): Missing collection item in cache
```

### Priority this issue should have

High (immediate attention needed)

**Comment by samuelvanderwaal** [comment]
Do you have the `collection.json` and `collection.png` files in your assets folder?

**Comment by luisrovirac** [comment]
Yes, I have the collection.json and collection.png files in your assets folder

**Comment by luisrovirac** [comment]
![Detail01](https://user-images.githubusercontent.com/38593025/226837702-8c31c725-9426-405c-8d34-95c056fe735a.jpeg)

**Comment by luisrovirac** [comment]
![solution01](https://user-images.githubusercontent.com/38593025/226863082-6bb67d31-2830-4eab-8a0e-e5d0058f498a.jpeg)

**Comment by luisrovirac** [comment]
Thanks for the excellent product.

**Comment by samuelvanderwaal** [comment]
@luisrovirac having a collection was optional on Candy Machine V2 (Sugar <= 1.2) but is mandatory on Candy Machine V3 (Sugar 2.0+).
