### ISSUE TITLE
[Bug]: Mainnet Candy Machine Number of items (11) do not match cache items (500). Item number in the config should only include asset files, not the collection file.

### ISSUE THREAD

**Issue by 3alola** [metaplex-foundation/sugar#445]
### Issue description

PS C:\Users\3alola\Desktop\Solana\metaplex-master\Carsolautofinal\MyProject> sugar deploy

Error running command (re-run needed): Number of items (11) do not match cache items (500).
Item number in the config should only include asset files, not the collection file.
PS C:\Users\xxx\Desktop\Solana\metaplex-master\Carsolautofinal\MyProject> sugar deploy
[1/2] Loading candy machine
[1/2] Loading candy machine
Candy machine ID: 7PJcK16etzbS8T179tGGkU5XQ8Qi87nv37xGiGFxxxxx

[2/2] Writing config lines
Sending config line(s) in 29 transaction(s): (Ctrl+C to abort)
[00:01:34] Deploy failed ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 0/29
Error running command (re-run needed): Command failed due to the following reason(s):
• Candy Machine: IndexGreaterThanLength: Index greater than length
• Candy Guard: DataIncrementLimitExceeded: Exceeded account increase limit

### Relevant log output

```shell
PS C:\Users\3alola\Desktop\Solana\metaplex-master\Carsolautofinal\MyProject> sugar deploy

Error running command (re-run needed): Number of items (11) do not match cache items (500).
Item number in the config should only include asset files, not the collection file.
PS C:\Users\xxx\Desktop\Solana\metaplex-master\Carsolautofinal\MyProject> sugar deploy
[1/2] Loading candy machine
[1/2] Loading candy machine
Candy machine ID: 7PJcK16etzbS8T179tGGkU5XQ8Qi87nv37xGiGFxxxxx

[2/2] Writing config lines
Sending config line(s) in 29 transaction(s): (Ctrl+C to abort)
[00:01:34] Deploy failed ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 0/29
Error running command (re-run needed): Command failed due to the following reason(s):
• Candy Machine: IndexGreaterThanLength: Index greater than length
• Candy Guard: DataIncrementLimitExceeded: Exceeded account increase limit
```

### Priority this issue should have

Low (slightly annoying)

**Comment by samuelvanderwaal** [comment]
@3alola What does your assets directory look like?
