### ISSUE TITLE
[Bug]: Sugar reveal - No URI found

### ISSUE THREAD

**Issue by cesar4design** [metaplex-foundation/sugar#451]
I did a CMv3 guards with hidden setting, i want to test the sugar reveal, but i get this error, what i did wrong? I just follow the guide. 

![image](https://github.com/metaplex-foundation/sugar/assets/75784005/2ea2c6b8-ffc1-4755-9652-2e39975c6920)

**Comment by cesar4design** [comment]
I think it may be due to the "collection image", but what should I call this? Can it be?

**Comment by samuelvanderwaal** [comment]
Can you post some examples of JSON metadata here or the links to the stored JSON metadata on NFT storage? I'm thinking your names in your metadata doesn't match what's in the cache.

**Comment by cesar4design** [comment]
> Can you post some examples of JSON metadata here or the links to the stored JSON metadata on NFT storage? I'm thinking your names in your metadata doesn't match what's in the cache.

The name of the NFTs in the metadata is the same as in the cache (attached image).

When this was not the case, I would get another type of error saying that the name did not match. 


![image](https://github.com/metaplex-foundation/sugar/assets/75784005/9cffb182-b087-4eb4-9325-93a90b5ec297)

**Comment by samuelvanderwaal** [comment]
> > Can you post some examples of JSON metadata here or the links to the stored JSON metadata on NFT storage? I'm thinking your names in your metadata doesn't match what's in the cache.
> 
> The name of the NFTs in the metadata is the same as in the cache (attached image).
> 
> When this was not the case, I would get another type of error saying that the name did not match.
> 
> ![image](https://user-images.githubusercontent.com/75784005/247539180-9cffb182-b087-4eb4-9325-93a90b5ec297.png)

Yeah, this is a bug. It's not expecting 0 indexed NFT names tho it's a valid use-case. I have a PR open to fix it.
