### ISSUE TITLE
[Bug]: sugar sign on mainnet-beta returns  HTTP status client error (410 Gone)

### ISSUE THREAD

**Issue by D39-Dev** [metaplex-foundation/sugar#479]
### Issue description

On a live environment, when collection is deployed, all nfts are minted, when you try to sign the minted nfts with `sugar sign` command, officila RPC always returns error:
`🛑 Error running command (re-run needed): HTTP status client error (410 Gone) for url (https://api.mainnet-beta.solana.com/)`
So question is: is this a bad request by sugar or feature not implemented on this RPC?
If not implemented, what are the RPC which support the newly minted NFC signing? 
Or there's an other way to sing your NFTs?

### Relevant log output

```shell
[dev@dev-c9 nfts]$ sugar sign
[1/3] 🖥  Initializing connection
▪▪▪▪▪ Connected

[2/3] 🔍 Fetching mint ids

🛑 Error running command (re-run needed): HTTP status client error (410 Gone) for url (https://api.mainnet-beta.solana.com/)
```

### Priority this issue should have

High (immediate attention needed)

**Comment by samuelvanderwaal** [comment]
> ### Issue description
> On a live environment, when collection is deployed, all nfts are minted, when you try to sign the minted nfts with `sugar sign` command, officila RPC always returns error: `🛑 Error running command (re-run needed): HTTP status client error (410 Gone) for url (https://api.mainnet-beta.solana.com/)` So question is: is this a bad request by sugar or feature not implemented on this RPC? If not implemented, what are the RPC which support the newly minted NFC signing? Or there's an other way to sing your NFTs?
> 
> ### Relevant log output
> ```shell
> [dev@dev-c9 nfts]$ sugar sign
> [1/3] 🖥  Initializing connection
> ▪▪▪▪▪ Connected
> 
> [2/3] 🔍 Fetching mint ids
> 
> 🛑 Error running command (re-run needed): HTTP status client error (410 Gone) for url (https://api.mainnet-beta.solana.com/)
> ```
> 
> ### Priority this issue should have
> High (immediate attention needed)

The public RPC `api.mainnet-beta.solana.com` doesn't support certain heavy RPC methods on certain programs like Token Metadata, which is why you're getting a 410 error. You can try using a custom RPC e.g. from Helius or QuickNode.
