### ISSUE TITLE
Can I mint 1 NFT few time(20 times) on sugar?

### ISSUE THREAD

**Issue by Flaming19** [metaplex-foundation/sugar#480]
### Issue description

I have 2 images(NFT) I need to mint each image at least 20 times(2 * 20 = 40 times) is it possible to make it in Solana with sugar?
Please provide a solution for this.

### Priority this issue should have

Low (slightly annoying)

**Comment by MarkSackerberg** [comment]
Yes, you can use hiddenSettings. It will only require one image + metadata pair (plus image + metadata for the collection itself.

https://developers.metaplex.com/candy-machine/sugar/configuration
