### ISSUE TITLE
[Bug]: creator not properly being recognized

### ISSUE THREAD

**Issue by 21e8** [metaplex-foundation/sugar#495]
### Issue description

I am not sure if this is a problem with explorers or my config.

I create a candy machine with this config:

```
{
  "tokenStandard": "nft",
  "number": 6,
  "symbol": "FIGS",
  "sellerFeeBasisPoints": 0,
  "isMutable": true,
  "isSequential": true,
  "creators": [
    {
      "address": "9LHp6NbV6i3t3bguU6HdyTCkBeb6N8E5P9skauYizsmK",
      "share": 100
    }
  ],
  "uploadMethod": "bundlr",
  "ruleSet": null,
  "awsConfig": null,
  "sdriveApiKey": null,
  "nftStorageAuthToken": null,
  "shdwStorageAccount": null,
  "pinataConfig": null,
  "hiddenSettings": null,
  "maxEditionSupply": 6,
  "guards": {
    "default": {
      "botTax": {
        "value": 0.00001,
        "lastInstruction": true
      }
    },
    "groups": [
      {
        "label": "Public",
        "guards": {
          "startDate": {
            "date": "2022-10-20 18:00:00 +0000"
          },
          "solPayment": {
            "value": 0.069,
            "destination": "9LHp6NbV6i3t3bguU6HdyTCkBeb6N8E5P9skauYizsmK"
          },
          "tokenGate": {
            "amount": 10000,
            "mint": "DpeJ6CkihBJzSNvgMcB9e56NT6Qiu2HL3nAGwYWUJESt"
          }
        }
      }
    ]
  }
}

```

finished cache.json (without guards)

```
  "program": {
    "candyMachine": "GsWLHeCFZvcW4awsP3r75EuVu4hhhWgPfrTXy5UFH3Vx",
    "candyGuard": "",
    "candyMachineCreator": "GSfuQRrF2bYnWUruaQgaNNLW6hcSpoG4u2b4d87QLG4G",
    "collectionMint": "Ax2YmLvyBcuomRcw7FFD3hN6w4Ke8vK99FhGqTceFBYu"
  },

```

I was assuming that the only creator will be "9LHp6NbV6i3t3bguU6HdyTCkBeb6N8E5P9skauYizsmK"

however, every explorer I see is showing me the address I used to init the machine, even after i resigned the authority.

![image](https://github.com/user-attachments/assets/46b4f420-c367-4437-a99a-4fade2a61859)

sugar displays it right

<img width="864" alt="image" src="https://github.com/user-attachments/assets/509049c1-e4de-4bea-b370-ecff19397f20">

So I am wondering if sugar/cmv3 is using sth here that isn't known to explorers?

Not sure if it has to do with the "verified" flag in the creators array. this doesn't matter for me for this mint since royalties are at 0% but it doesn't help me instill trust either. 

### Relevant log output

```shell
madbook@madbook candy-machine-tenfigs % sugar show
[1/1] 🔍 Looking up candy machine

🍬 Candy machine ID: BN89QBZWXutBvS96CyhF37vHfVchp3HEnc31guCih9qr
 :
 :.. authority: 9LHp6NbV6i3t3bguU6HdyTCkBeb6N8E5P9skauYizsmK
 :.. mint authority: G6jz7zquxxiPZJxJ8vgpbxwzfQfLuyoh1aDm7XzzYSYQ
 :.. collection mint: HRh8LFvP1bsfPkEL8Xvr6dUqyAAdCqAm2QnavmhnQyDw
 :.. account version: V2
 :.. token standard: NonFungible
 :.. features: none
 :.. max supply: 0
 :.. items redeemed: 5
 :.. items available: 2000
 :.. symbol: FIGS
 :.. seller fee basis points: 0% (0)
 :.. is mutable: true
 :.. creators: 
 :   :.. 1: 9LHp6NbV6i3t3bguU6HdyTCkBeb6N8E5P9skauYizsmK (100%)
 :.. hidden settings: none
 :.. config line settings: 
     :.. prefix_name: FIGS PRESALE TOKEN
     :.. name_length: 0
     :.. prefix_uri: https://shdw-drive.genesysgo.net/35PiJQEJDtZym2VsJQWYKC6UJUTdRy2K2xFJHAMS8nBU/nft-metadata.json
     :.. uri_length: 0
     :.. is_sequential: true
```

### Priority this issue should have

Low (slightly annoying)

generally speaking, there seems to be no documentation on the config file so a little explanation would def help

**Comment by MarkSackerberg** [comment]
If i am seeing it correctly the NFT you linked is the collection, correct? Are you sure that NFTs minted from the candy machine also would not have 9LHp6NbV6i3t3bguU6HdyTCkBeb6N8E5P9skauYizsmK as creator? It should have 9LHp6NbV6i3t3bguU6HdyTCkBeb6N8E5P9skauYizsmK and an additional one with 0% royalties derived from the CM.

Regarding the missing docs, that could be found here: https://developers.metaplex.com/candy-machine/sugar/configuration

**Comment by 21e8** [comment]
Turns out I was probably looking at the collection mint which in our case is identical to the actual mint.

Sorry to bother!
